# Generated by scripts/update-formula.sh on every release — do not edit by hand.
#
# The tap lives in the agentstow repository itself rather than a separate
# homebrew-agentstow one, so it is tapped by URL:
#
#   brew tap agentstow/tap https://github.com/agentstow/agentstow
#   brew install agentstow
class Agentstow < Formula
  desc "One canonical .agents/ folder, fanned out to all your AI coding agents"
  homepage "https://github.com/agentstow/agentstow"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/agentstow/agentstow/releases/download/v2.0.6/agentstow-2.0.6-darwin-arm64.tar.gz"
      sha256 "859854a4c2b33b76caa4d5017e22b5bba51e324e7792ab163185493b92d5f443"
    end
    on_intel do
      url "https://github.com/agentstow/agentstow/releases/download/v2.0.6/agentstow-2.0.6-darwin-x64.tar.gz"
      sha256 "df57b11398a8483d315680c5706620d82c2fd073041b4b213c115a54b77856b5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/agentstow/agentstow/releases/download/v2.0.6/agentstow-2.0.6-linux-arm64.tar.gz"
      sha256 "7ff8eba69b510ef5327dd70b03f5ae21d362dc453fc3dab320147dcfe6151384"
    end
    on_intel do
      url "https://github.com/agentstow/agentstow/releases/download/v2.0.6/agentstow-2.0.6-linux-x64.tar.gz"
      sha256 "3b869c4320d146c050d90a6630a7f810350ee9e498b7a83b776de662a008dcef"
    end
  end

  def install
    bin.install "agentstow"
  end

  test do
    assert_match "agentstow #{version}", shell_output("#{bin}/agentstow --version")
  end
end
