# Generated by scripts/update-formula.sh on every release — do not edit by hand.
#
# The tap lives in the agent-sync repository itself rather than a separate
# homebrew-agent-sync one, so it is tapped by URL:
#
#   brew tap agent-sync-sh/tap https://github.com/agent-sync-sh/agent-sync
#   brew install agent-sync
class AgentSync < Formula
  desc "One canonical .agents/ folder, fanned out to all your AI coding agents"
  homepage "https://agent-sync.sh"
  license "MIT"
  version "1.0.0"

  on_macos do
    on_arm do
      url "https://github.com/agent-sync-sh/agent-sync/releases/download/agent-sync-v1.0.0/agent-sync-1.0.0-darwin-arm64.tar.gz"
      sha256 "b352b234fb99f30994ac575d6a2d701709aced6c8697b631ae39944145dcd5de"
    end
    on_intel do
      url "https://github.com/agent-sync-sh/agent-sync/releases/download/agent-sync-v1.0.0/agent-sync-1.0.0-darwin-x64.tar.gz"
      sha256 "51de6ae6a043bf4fef9026bc25ed1e4d8e14256bcc0a04075ee55277963b2105"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/agent-sync-sh/agent-sync/releases/download/agent-sync-v1.0.0/agent-sync-1.0.0-linux-arm64.tar.gz"
      sha256 "e6a25d53f3f661d6b6c87cb3eae69530ac43c4ff070311d42193a0dcbb588c26"
    end
    on_intel do
      url "https://github.com/agent-sync-sh/agent-sync/releases/download/agent-sync-v1.0.0/agent-sync-1.0.0-linux-x64.tar.gz"
      sha256 "949e80be56c982d949be900ab5725523230fcde90aecd9037bf0d106e6ec9721"
    end
  end

  def install
    bin.install "agent-sync"
  end

  test do
    assert_match "agent-sync #{version}", shell_output("#{bin}/agent-sync --version")
  end
end
