# Generated by scripts/update-formula.sh on every release — do not edit by hand.
#
# The tap lives in the agent-sync repository itself rather than a separate
# homebrew-agent-sync one, so it is tapped by URL:
#
#   brew tap agent-sync-sh/tap https://github.com/agent-sync-sh/agent-sync
#   brew install agent-sync
class AgentSync < Formula
  desc "One canonical .agents/ folder, fanned out to all your AI coding agents"
  homepage "https://agent-sync.sh"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/agent-sync-sh/agent-sync/releases/download/agent-sync-v1.1.0/agent-sync-1.1.0-darwin-arm64.tar.gz"
      sha256 "bccbdef28d8a2bc58a1eebfb0930cde5ab2b70251dd2e83148d652ab38ac83cd"
    end
    on_intel do
      url "https://github.com/agent-sync-sh/agent-sync/releases/download/agent-sync-v1.1.0/agent-sync-1.1.0-darwin-x64.tar.gz"
      sha256 "f332eba97df1faae3a4a20c63ebd3be48ed49d7b8e405072012fa1f599b81fb9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/agent-sync-sh/agent-sync/releases/download/agent-sync-v1.1.0/agent-sync-1.1.0-linux-arm64.tar.gz"
      sha256 "90b47a6fe76a161b280457bd8303128258ae4486f1512501fec58909e324a22f"
    end
    on_intel do
      url "https://github.com/agent-sync-sh/agent-sync/releases/download/agent-sync-v1.1.0/agent-sync-1.1.0-linux-x64.tar.gz"
      sha256 "83196115ef7460853ee31a4129b16bf8f324d9e528bf40ecf07ddf0a8a9ab4c3"
    end
  end

  def install
    bin.install "agent-sync"
  end

  test do
    assert_match "agent-sync #{version}", shell_output("#{bin}/agent-sync --version")
  end
end
