# Generated by scripts/update-formula.sh on every release — do not edit by hand.
#
# The tap lives in the agent-sync repository itself rather than a separate
# homebrew-agent-sync one, so it is tapped by URL:
#
#   brew tap agent-sync-sh/tap https://github.com/agent-sync-sh/agent-sync
#   brew install agent-sync
class AgentSync < Formula
  desc "One canonical .agents/ folder, fanned out to all your AI coding agents"
  homepage "https://agent-sync.sh"
  version "1.0.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/agent-sync-sh/agent-sync/releases/download/agent-sync-v1.0.1/agent-sync-1.0.1-darwin-arm64.tar.gz"
      sha256 "b69e936290685980cf686ae67f05028150f73657b43419a2adb1d93986f4e42e"
    end
    on_intel do
      url "https://github.com/agent-sync-sh/agent-sync/releases/download/agent-sync-v1.0.1/agent-sync-1.0.1-darwin-x64.tar.gz"
      sha256 "94aacce129a0c937375e2eb9a35476679ed6cbcc70962173f827567c040d1786"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/agent-sync-sh/agent-sync/releases/download/agent-sync-v1.0.1/agent-sync-1.0.1-linux-arm64.tar.gz"
      sha256 "2c9e648f5790888f7e96c406b306228963cfd6c92e8e12c293a7e9a0abd8fa13"
    end
    on_intel do
      url "https://github.com/agent-sync-sh/agent-sync/releases/download/agent-sync-v1.0.1/agent-sync-1.0.1-linux-x64.tar.gz"
      sha256 "a7abd28bfc418a860173c455533aba60c78c7afd6f1091b4096db5cab6a2232c"
    end
  end

  def install
    bin.install "agent-sync"
  end

  test do
    assert_match "agent-sync #{version}", shell_output("#{bin}/agent-sync --version")
  end
end
