# Generated by scripts/update-formula.sh on every release — do not edit by hand.
#
# The tap lives in the agentstow repository itself rather than a separate
# homebrew-agentstow one, so it is tapped by URL:
#
#   brew tap agentstow/tap https://github.com/agentstow/agentstow
#   brew install agentstow
class Agentstow < Formula
  desc "One canonical .agents/ folder, fanned out to all your AI coding agents"
  homepage "https://github.com/agentstow/agentstow"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/agentstow/agentstow/releases/download/v2.0.6/agentstow-2.0.6-darwin-arm64.tar.gz"
      sha256 "64be078f8cbb8ecb7ab17fadb923132d744b3e589a3c4215aba81abeb114a8fe"
    end
    on_intel do
      url "https://github.com/agentstow/agentstow/releases/download/v2.0.6/agentstow-2.0.6-darwin-x64.tar.gz"
      sha256 "6f32629d1e169f2daba2a4624b34df0602eb6a351088bf68f1e11a7c46cf8672"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/agentstow/agentstow/releases/download/v2.0.6/agentstow-2.0.6-linux-arm64.tar.gz"
      sha256 "30eb0bf5d23674adffb3e7e839b9888a7296539d03a23898fccd2b914fc332e1"
    end
    on_intel do
      url "https://github.com/agentstow/agentstow/releases/download/v2.0.6/agentstow-2.0.6-linux-x64.tar.gz"
      sha256 "02236e3a27986d1f7a8af1ebc4d2a9965fe92bdbcfbb84a374201c6a02533113"
    end
  end

  def install
    bin.install "agentstow"
  end

  test do
    assert_match "agentstow #{version}", shell_output("#{bin}/agentstow --version")
  end
end
