#!/usr/bin/env bash
# Rewrite Formula/agent-sync.rb to point at the release assets of one tag.
#
#   scripts/update-formula.sh <tag>
#
# The checksums come from the SHA256SUMS.txt already published on that release,
# so the formula can only ever describe assets that exist. The whole file is
# regenerated rather than patched: there is no half-updated state where the
# version says one thing and a sha256 still says another.
#
# The `tap` job in .github/workflows/release.yml runs this on every release tag
# and commits the result to main; running it by hand is the manual fallback.
set -euo pipefail

REPO="${AGENT_SYNC_REPO:-agent-sync-sh/agent-sync}"
TARGETS="darwin-arm64 darwin-x64 linux-arm64 linux-x64"

tag="${1:-}"
if [ -z "$tag" ]; then
  echo "usage: scripts/update-formula.sh <tag>   (e.g. agent-sync-v1.0.0)" >&2
  exit 2
fi
# The agent-sync line tags agent-sync-v*; the agentstow line tagged plain v*.
# Stripping both in order leaves the bare version whichever line the tag is on.
version="${tag#agent-sync-v}"
version="${version#v}"

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

gh release download "$tag" --repo "$REPO" --pattern SHA256SUMS.txt --dir "$tmp" --clobber

# sha256sum writes "<hash>  <name>", and "<hash> *<name>" in binary mode; match
# either rather than assuming which one produced the file.
sum_for() {
  awk -v want="agent-sync-$version-$1.tar.gz" \
    '$2 == want || $2 == "*" want { print $1 }' "$tmp/SHA256SUMS.txt" | head -1
}

for target in $TARGETS; do
  if ! [[ "$(sum_for "$target")" =~ ^[0-9a-f]{64}$ ]]; then
    echo "no sha256 for agent-sync-$version-$target.tar.gz in the $tag SHA256SUMS.txt" >&2
    exit 1
  fi
done

asset() { echo "https://github.com/$REPO/releases/download/$tag/agent-sync-$version-$1.tar.gz"; }

mkdir -p "$root/Formula"
cat > "$root/Formula/agent-sync.rb" <<RUBY
# Generated by scripts/update-formula.sh on every release — do not edit by hand.
#
# The tap lives in the agent-sync repository itself rather than a separate
# homebrew-agent-sync one, so it is tapped by URL:
#
#   brew tap agent-sync-sh/tap https://github.com/$REPO
#   brew install agent-sync
class AgentSync < Formula
  desc "One canonical .agents/ folder, fanned out to all your AI coding agents"
  homepage "https://agent-sync.sh"
  license "MIT"

  on_macos do
    on_arm do
      url "$(asset darwin-arm64)"
      sha256 "$(sum_for darwin-arm64)"
    end
    on_intel do
      url "$(asset darwin-x64)"
      sha256 "$(sum_for darwin-x64)"
    end
  end

  on_linux do
    on_arm do
      url "$(asset linux-arm64)"
      sha256 "$(sum_for linux-arm64)"
    end
    on_intel do
      url "$(asset linux-x64)"
      sha256 "$(sum_for linux-x64)"
    end
  end

  def install
    bin.install "agent-sync"
  end

  test do
    assert_match "agent-sync #{version}", shell_output("#{bin}/agent-sync --version")
  end
end
RUBY

echo "Formula/agent-sync.rb now points at $tag"
